In [1]:
import pandas as pd
import numpy as np
from db_connector import db

sf_tape = open(".\\sql\\sf_tape.sql", 'r').read()
df = db.get_data(sf_tape)

In [17]:
df['payment_received_usd'].fillna(0, inplace=True)

In [48]:
d = pd.read_pickle('sf_tape.pkl')
d

,id,reference,entity,invoice_id,exporter_user_id,importer_user_id,exporter_country,buyer_country,buyer_country_risk_category,buyer_insurance_grade,...,margin_received_usd,buyer_advance_to_seller_usd,advance_rate_net_of_margin,cash_payment_received_usd,cash_advance_disbursed_usd,exporter_company_name,importer_company_name,latest_due_date,vin_mnth,vin_qtr
0,1,44,None,1,10,3,India,United States Of America,Low,5.0,...,None,None,None,0.0,0.0,Dhara Foods Private Limited,"SHRINATH TRADING, LLC.",2016-04-03,2016-02,2016Q1
1,2,45,None,2,10,3,India,United States Of America,Low,5.0,...,None,None,None,0.0,0.0,Dhara Foods Private Limited,"SHRINATH TRADING, LLC.",2016-04-03,2016-02,2016Q1
2,3,49,None,3,10,4,India,United States Of America,Low,NaN,...,None,None,None,0.0,0.0,Dhara Foods Private Limited,Daxa Foods Inc.,2016-04-16,2016-02,2016Q1
3,4,53,None,4,10,3,India,United States Of America,Low,5.0,...,None,None,None,0.0,0.0,Dhara Foods Private Limited,"SHRINATH TRADING, LLC.",2016-05-29,2016-03,2016Q1
4,5,1058,None,5,11,5,India,United States Of America,Low,7.0,...,None,None,None,0.0,0.0,Kohlico Foods and Beverages Private Limited,Shah Distributors Inc.,2016-05-17,2016-03,2016Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54427,60853,A4538,None,62010,156188,156857,Mexico,Mexico,Medium,3.0,...,None,None,None,0.0,0.0,Jesus Ocegueda Gomez,LAS CERVEZAS MODELO EN NAYARIT,2022-01-03,2021-11,2021Q4
54428,60854,A4534,None,62011,156188,139044,Mexico,Mexico,Medium,3.0,...,None,None,None,0.0,0.0,Jesus Ocegueda Gomez,PUNTO A PUNTO T2S. DE R.L. DE C.V,2022-01-03,2021-11,2021Q4
54429,60855,A4536,None,62012,156188,139044,Mexico,Mexico,Medium,3.0,...,None,None,None,0.0,0.0,Jesus Ocegueda Gomez,PUNTO A PUNTO T2S. DE R.L. DE C.V,2022-01-03,2021-11,2021Q4
54430,60856,A4535,None,62013,156188,139044,Mexico,Mexico,Medium,3.0,...,None,None,None,0.0,0.0,Jesus Ocegueda Gomez,PUNTO A PUNTO T2S. DE R.L. DE C.V,2022-01-03,2021-11,2021Q4
54431,60857,A4528,None,62014,156188,139044,Mexico,Mexico,Medium,3.0,...,None,None,None,0.0,0.0,Jesus Ocegueda Gomez,PUNTO A PUNTO T2S. DE R.L. DE C.V,2022-01-03,2021-11,2021Q4